### ISSUE TITLE
exception while go.getPlayerProfile(true)

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#104]
while doing go.getPlayerProfile(true) (after begin logged)

it throw this excepiton

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:119)
    at com.pokegoapi.api.PokemonGo.getPlayerAndUpdateInventory(PokemonGo.java:101)
    at com.pokegoapi.api.PokemonGo.getPlayerProfile(PokemonGo.java:154)


```

it's even possible that's correct, but will be better imho if it throw something more understandable or a custom exception?

**Comment by jabbink** [comment]
Did you do multiple requests via the same `PokemonGo` instance (eg. multi threaded?) because that's when I encounter it.

Right now, this API is **not** thread safe!

**Comment by ramarro123** [comment]
yep, that was the problem :) tnx!
