### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#116]
Yesterday my code worked like a charm..
Now its throwing this exception at me like crazy, maybe the developer of pokemonGo changed something that we need to adapt to?

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:171)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:143)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:89)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:79)
    at com.pokegoapi.api.map.Map.getRetainedMapObject(Map.java:50)
    at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:63)
    at de.busybeever.pokemongo.pokemonfinder.PokemonFinder$1.run(PokemonFinder.java:44)
    at java.lang.Thread.run(Unknown Source)
//This is my line 44 in PokemonFinder
List<CatchablePokemon> li = pokemonGo.getMap().getCatchablePokemon();

**Comment by stirante** [comment]
Servers are pretty down right now. I can't even login.

http://ispokemongodownornot.com/

**Comment by ramarro123** [comment]
i got this error when server start to get crazy :)

**Comment by ghost** [comment]
Oh yeah I see just tried to log in with my mobile. RIP
