### ISSUE TITLE
PTC login issue

### ISSUE THREAD

**Issue by DiogoRNeves** [Grover-c13/PokeGOAPI-Java#150]
Im using a PTC Login.

After a large amount of time (I've had this after an hour or after 2 and a half hours) it starts looping over this:

```
Getting map of (COORDS, COORDS)
D/RequestHandler: Authenticated with static token
Exception in thread "Thread-2114" com.pokegoapi.exceptions.LoginFailedException
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:238)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:163)
```

When I stop and restart the bot it gets on perfectly again, as long as I'm not authenticating with token. So I was thinking if you could get a count of the amount of times this error comes up and then force it to use user/pw login after, idk, 5?

**Comment by Grover-c13** [comment]
This should be corrected in the dev branch now with refresh tokens implemented.
