### ISSUE TITLE
Every login attempt fails

### ISSUE THREAD

**Issue by pvanassen** [Grover-c13/PokeGOAPI-Java#176]
Every login attempt fails with the following exception: 
com.pokegoapi.exceptions.LoginFailedException: Refreshing token failed Error  in API Url 

```
E/Main: Failed to login or server issue: 
com.pokegoapi.exceptions.LoginFailedException: Refreshing token failed Error  in API Url 
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:141)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
    at nl.pvanassen.pokemon.Main.main(Main.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

This is fixed by reverting commits:
ccf016dd2c5da122763b14a2a06b500e5c08e890
7ccf228edcc0615cdf441b027a7925bc3db309da

**Comment by SonnyX** [comment]
For some reason the login-script does not fetch an refresh token. therefor it stays null, whenever the current token expires and the refresh token is null you get this error.
Edit: Forgot to mention that the error should occur for everybody.

**Comment by rajulbhatnagar** [comment]
You should get a refreshToken if u call GoogleLogin.login()
Then next time you can call GoogleLogin.login("tokenid if u have 1 or empty string","refreshtoken that you should have persisted")

Only the call to GoogleLogin.login() sets the refresh token. How are u guys using the API.

**Comment by rajulbhatnagar** [comment]
This is the login flow we use for google auth
https://developers.google.com/identity/protocols/OAuth2ForDevices#overview

**Comment by ramarro123** [comment]
i have the same issue with PtcLogin login as well, so it's not just the google auth the problem

**Comment by pvanassen** [comment]
The com.pokegoapi.auth.GoogleLogin#login(java.lang.String, java.lang.String) method used to accept username + password. It has been rewritten to accept token + refresh token. Now there's no way to initially login with username + password.

**Comment by rajulbhatnagar** [comment]
Username and Password was never used for Google Login by the api. As in the values passed were ignored.

**Comment by pvanassen** [comment]
Nope indeed. Just the login() call should be enough.
