### ISSUE TITLE
Hatching four eggs, got out of bounds error

### ISSUE THREAD

**Issue by swiftveteran** [Grover-c13/PokeGOAPI-Java#189]
There are four eggs to hatch but it gets an out of bounds error.

```
Exception in thread "Thread-4" java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.getExperienceAwarded(GetHatchedEggsResponseOuterClass.java:292)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:77)
```

Additionally, it loses track of incubators:

```
24 Jul 11:58:50: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING 
```

**Comment by stirante** [comment]
Once this PR gets commited it will work perfectly. I'm using it myself.

https://github.com/AeonLucid/POGOProtos/pull/54

**Comment by vmarchaud** [comment]
I think this is more a server problem than a proto problem, since the problem here is that the server isnt sending the experience awarded for this hetched egg, i will look if we can get a protection for this.

**Comment by jabbink** [comment]
FYI: That thing got merged some time ago, so all someone needs to do is update the submodule.
