### ISSUE TITLE
OkHttpClient class def not found

### ISSUE THREAD

**Issue by Zaminox** [Grover-c13/PokeGOAPI-Java#215]
**Description:**
The OkHttpClient class def not found.

**Steps to reproduce:**
1. Create an OkHttpClient instance

**Expected behavior:**
The program can find the OkHttpClient and connect to the Pokémon GO account

**Actual behavior:**
OkHttpClient can't be found

**Stacktrace (If it's a crash):**
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
    at fr.zaminox.CheatGO.initialize(CheatGO.java:18)
    at fr.zaminox.CheatGO.<init>(CheatGO.java:14)
    at fr.zaminox.CheatGO.main(CheatGO.java:36)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 3 more

**Version:**
master-SNAPSHOT

**Comment by FabianTerhorst** [comment]
You added the okhttp dependencie?

**Comment by Zaminox** [comment]
I found the problem it's the Maven project, Gradle works.
