### ISSUE TITLE
LoginFailedException: Refreshing token failed Error in API Url

### ISSUE THREAD

**Issue by navopw** [Grover-c13/PokeGOAPI-Java#241]
What i'm trying:
- Login with GoogleLogin + OnGoogleLoginOAuthCompleteListener

Version:
- Current Development branch, because I need the OnGoogleLoginOAuthCompleteListener

```
com.pokegoapi.exceptions.LoginFailedException: Refreshing token failed Error  in API Url 
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:141)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
    at de.navo.gogui.ui.LoginGui.loginButtonActionPerformed(LoginGui.java:89)
    at de.navo.gogui.ui.LoginGui.access$000(LoginGui.java:21)
    at de.navo.gogui.ui.LoginGui$1.actionPerformed(LoginGui.java:40)`

I get this exception, does anyone know why?
```

**Comment by jcady** [comment]
Same problem is happening to me. Using the ID token and refresh token I retrieved initially as parameters to the GoogleLogin. Works fine when first created (and while ID token is still valid). But it seems like as soon as it needs to refresh, it fails with this exception.

**Comment by vmarchaud** [comment]
Should be working with the latest dev branch. Reopen if it isnt the case

**Comment by dtitov** [comment]
I'm also facing this issue (I'm on revision 7166dcc of master):

```
D/RequestHandler: Authenticated with static token

Error  in API Url 

com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:204) ~[PokeGOAPI-Java-7166dcc.jar:na]
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:277) ~[PokeGOAPI-Java-7166dcc.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

My bot worked for about 1.5 hours and then started to throw this thing...
