### ISSUE TITLE
CatchPokemonAtAreaExample FATAL EXCEPTION

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#255]
When i run CatchPokemonAtAreaExample on Android Studio the app crash with this error:
`07-26 19:43:38.192 17990-17990/com.example.mpcom.testapi30 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.mpcom.testapi30, PID: 17990
                                                                             android.os.NetworkOnMainThreadException
                                                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                                 at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
                                                                                 at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                                 at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                                 at okhttp3.Dns$1.lookup(Dns.java:39)
                                                                                 at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
                                                                                 at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
                                                                                 at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
                                                                                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
                                                                                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                 at com.pokegoapi.auth.PtcCredentialProvider$2.intercept(PtcCredentialProvider.java:95)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                                 at okhttp3.RealCall.execute(RealCall.java:60)
                                                                                 at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:120)
                                                                                 at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:101)
                                                                                 at com.pokegoapi.examples.CatchPokemonAtAreaExample.main(CatchPokemonAtAreaExample.java:62)
                                                                                 at com.example.mpcom.testapi30.MainActivity$1.onClick(MainActivity.java:33)
                                                                                 at android.view.View.performClick(View.java:5197)
                                                                                 at android.view.View$PerformClick.run(View.java:20926)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`
What is the problem?

**Comment by langerhans** [comment]
`NetworkOnMainThreadException` 

It's right there, hiding in plain sight. I'll let you figure out how to copy/paste that to Google :+1:

**Comment by guipenedo** [comment]
You'll need to run that on a new thread/asynctask. You can't run network stuff on the UI thread.

**Comment by ghost** [comment]
@langerhans I have searched on google but I haven't found any working 
answers.

**Comment by ghost** [comment]
@guipenedo i have used this code on MainActivity
`EXA=new String[1];
button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
            CatchPokemonAtAreaExample.main(EXA);
            }
        });`but it doesn't work,  what I'm doing wrong?

**Comment by jeremyheaton** [comment]
As was stated before, you are running it on the main ui thread. You'll need to run it on a different thread. Android supports this with the async task. 

https://developer.android.com/reference/android/os/AsyncTask.html

**Comment by ghost** [comment]
ok, thanks

**Comment by EdbertChan** [comment]
Read the Android FAQ in the Readme.
