### ISSUE TITLE
How do I properly use the Auth and Login functions?

### ISSUE THREAD

**Issue by JohnTendik** [Grover-c13/PokeGOAPI-Java#266]
#**Description:**
I can't seem to get the login to work, well I can one way, but can't another way. 

My previous code looked like this:
`
auth = new GoogleLogin(okHttpClients[0]).login("","");
PokemonGo go = new PokemonGo(auth,httpclient);
`
This way, I'm able to log in, and get that console message
"Get user to go to:https://www.google.com/device and enter code:xxxx-xxxx"

Once I entered the the code on the website, the api worked and I was able to interact with it. However my question is am I able to get that code any way other than the console? If I build the apk and put it on my phone I can't see the code or the link because no console. How can I get that code?

btw this is with the master branch code.

So the first way is working fine, but I noticed the github guide changed, and the new code looks like this
`PokemonGo go = new PokemonGo(new GoogleCredentialProvider(okHttpClients,listnr),okHttpClients);`

I tried this, and I got a not resolved for GoogleCredentialProvider. I changed my gradle app dependency to the Development branch and GoogleCredentialProvider is now available.
Using this code, I get to this stage:
`I/System.out: D/GoogleCredentialProvider: Get user to go to:https://www.google.com/device and enter code:xxxx-xxxx`

Once I enter the code however, my app crashed and I get this FATAL error:

`
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                          Process: com.thirdeye.john.lazygo, PID: 25170
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.NoSuchMethodError: No direct method <init>(Lcom/pokegoapi/auth/CredentialProvider;Lokhttp3/OkHttpClient;)V in class Lcom/pokegoapi/api/PokemonGo; or its super classes (declaration of 'com.pokegoapi.api.PokemonGo' appears in /data/data/com.thirdeye.john.lazygo/files/instant-run/dex/slice-PokeGOAPI-Java-master-SNAPSHOT_6b60f87c89478b51844fe3220bf3d89a8a179ab3-classes.dex)
                                                                              at com.thirdeye.john.lazygo.MainActivity$setupPogo.doInBackground(MainActivity.java:490)
                                                                              at com.thirdeye.john.lazygo.MainActivity$setupPogo.doInBackground(MainActivity.java:474)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
`

Which method am I supposed to use? The second one is producing an error but I'm not sure if that's because I'm not using the code correctly.

**Comment by JohnTendik** [comment]
Ok so I suppose because the dev branch is always changing it may have had issues because it seems to be working now, however my original question I would still like some guidance on. 

How am I able to copy the xxxx-xxxx code that I need to enter into the devices page pragmatically? If I build the apk and put it on my phone I can't see the code because I can't access the dev console on my phone. Any tips?

**Comment by Grover-c13** [comment]
You implement a Listener:
`
public interface OnGoogleLoginOAuthCompleteListener {

```
    void onInitialOAuthComplete(GoogleAuthJson googleAuthJson);

    void onTokenIdReceived(GoogleAuthTokenJson googleAuthTokenJson);
```

}
`

The GoogleAuthJson contains all the data:
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/auth/GoogleAuthJson.java

**Comment by JohnTendik** [comment]
Wow that was easy :P Brilliant, Thank you for the help!
