### ISSUE TITLE
Pokestop error

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#288]
When i execute this code on android studio in Background :
`private FortData dat;`
`private long cooldownCompleteTimestampMs;`
`PokemonGo go = new PokemonGo(new PtcCredentialProvider(http, MainActivity.LOGIN,
                        MainActivity.PASSWORD), http);`
`Pokestop rifornimenti= new Pokestop(go,dat);`

The app crashes with this error:
`AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                            Process: com.example.mpcom.mapstest, PID: 23965
                                                                            java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long POGOProtos.Map.Fort.FortDataOuterClass$FortData.getCooldownCompleteTimestampMs()' on a null object reference
                                                                                at com.pokegoapi.api.map.fort.Pokestop.<init>(Pokestop.java:56)
                                                                                at com.example.mpcom.mapstest.Test.doInBackground(Test.java:42)
                                                                                at com.example.mpcom.mapstest.Test.doInBackground(Test.java:26)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                at java.lang.Thread.run(Thread.java:818) `
why?The problem is getCooldownCompleteTimestampMs but i don't understand what I'm doing wrong.

**Comment by Aphoh** [comment]
dat is null. You aren't initializing it.

**Comment by ghost** [comment]
@Aphoh How do I initializing it?thanks

**Comment by Aphoh** [comment]
Currently I'm not sure. Some lines seem to be commented out in the Map file.

**Comment by Aphoh** [comment]
@mpcom00 Ah, calling pokemonGo.getMap().getMapObjects().getPokestops() should work

**Comment by ghost** [comment]
@Aphoh Excuse me, but i don't understand how to solve the error. Can you post the code?Thanks

**Comment by Grover-c13** [comment]
You should not be constructing these objects unless you really need to (and have a good understanding of the structure of the API), the API is meant to create these wrapper objects, calling your go.getMap().getMapObjects().getPokestops() will give you a list of Pokestop objects that are created with the data from the server.
