### ISSUE TITLE
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by KyleBoyer** [Grover-c13/PokeGOAPI-Java#325]
Stack trace:

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:177)
    at ink.abb.pogo.scraper.tasks.Walk.run(Walk.kt:50)
    at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
    at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:54)
    at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
    at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:118)
    at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
    at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
    at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:175)
    ... 9 more

**Comment by vmarchaud** [comment]
This exception is always thrown when the server is sending invalid data, plus you are using a bot, go ask to the author for support.

**Comment by bolds07** [comment]
for sure there are several reasons to this exception be thrown.

I just identified that when you have the inventory with more items than the capacity is one of the situations.

for example if you have the full itembag and then you pass next level... so the server will give you a bonus and when you try to update your itembag next time you will get this exception

**Comment by vmarchaud** [comment]
@bolds07 If you read the stacktrace, you'll see that the issue is `com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:177)`.
So again, the servers might not be stable enought.
