### ISSUE TITLE
InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by TheLushpen** [Grover-c13/PokeGOAPI-Java#333]
When try to call findCatchablePokemon app falls with error:

com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
                                              at com.pokegoapi.api.map.Map.getMapObjects(Map.java:287)
                                              at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250)
                                              at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185)
                                              at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
                                              at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:101)

On version:
compile 'com.github.Grover-c13:PokeGOAPI-Java:2e14fab7f0'

**Comment by Hindi** [comment]
#331
