### ISSUE TITLE
PTC-Login: Always getting com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token

### ISSUE THREAD

**Issue by clangdev** [Grover-c13/PokeGOAPI-Java#391]
Just taking first steps using lates Development-Branch with precompiled lib from build\libs\PokeGOAPI-Java-0.0.1-SNAPSHOT.jar
Google-Login works fine.
PTC-Login troubles me.
Please help if I miss something or maybe PTC-Service is down or API has error?

```
OkHttpClient httpClient = new OkHttpClient();
new PokemonGo(new PtcCredentialProvider(httpClient, username, password), httpClient);
```

Results in error.

```
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token
    at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:239)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:108)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:121)
    at PoGoScanner.<init>(PoGoScanner.java:74)
    at PoGoScanner.main(PoGoScanner.java:151)
```

**Comment by wanggang1987** [comment]
I mate the almost same issue 
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token, body:error=invalid_request
    at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:240)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:109)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:122)

**Comment by MenosGrante** [comment]
Gettings just the same error. Using `compile 'com.github.Grover-c13:PokeGOAPI-Java:0.3'` from JitPack.
Stack trace:

```
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token, body:error=invalid_request
at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:240)
at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:109)
at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:122)
at com.itemstudio.gean.MainActivity.onCreate(MainActivity.java:27)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by FabianTerhorst** [comment]
and when you use compile 'com.pokegoapi:PokeGOAPI-library:0.3.2' with maven {
            url  "http://dl.bintray.com/grover-c13/maven"
        }
        maven {
            url  "https://jitpack.io"
        }

**Comment by MenosGrante** [comment]
@FabianTerhorst gettings same error (`Failed to fetch token, body:error=invalid_request`) with your version of library.

**Comment by FabianTerhorst** [comment]
its not my version, will be the next release.

**Comment by MenosGrante** [comment]
@FabianTerhorst sorry, i mean version that you linked for us.

**Comment by vmarchaud** [comment]
should come from your network settings or just the PTC that was down.
