### ISSUE TITLE
Retrieval of map objects for catchablePokemon throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by loicortola** [Grover-c13/PokeGOAPI-Java#403]
**Description:**
When trying to get catchable pokemons (NianticManager.getCatchablePokemon), an exception is raised when trying to retrieve map objects.
@see Map.getMapObjects(List<Long> cellIds)

**Steps to reproduce:**
1. Login
2. Get catchable pokemons

**Expected behavior:**
Lots of pokemons <3

**Actual behavior:**
IndexOutOfBoundsException raised

**Stacktrace (If it's a crash):**
ST is caught by the Exception handler so no app crash,

**Version:**
Latest commit

**Comment by Grover-c13** [comment]
Master or dev?

**Comment by Grover-c13** [comment]
Also how are you getting the list of cellids

**Comment by loicortola** [comment]
Dev (sorry, I am currently AFK until tonight)
Le 31 juil. 2016 6:04 PM, Grover-c13 notifications@github.com a écrit :Master or dev?

**Comment by loicortola** [comment]
More info on this:

> > Getting the list of cellIds actually works well. 
> > It is the getMapObjects which doesn't work properly.
> > Raised: java.lang.IndexOutOfBoundsException: End index: 4098 >= 4096"
> > in NianticManager.getCatchablePokemon()

StackTrace:
java.lang.IndexOutOfBoundsException: End index: 4098 >= 4096
                    at com.google.protobuf.ByteString.checkRange(ByteString.java:1219)
                    at com.google.protobuf.ByteString.copyTo(ByteString.java:596)
                    at com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1101)
                    at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:1035)
                    at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:139)
                    at POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass$GetMapObjectsResponse.<init>(GetMapObjectsResponseOuterClass.java:78)
                    at POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass$GetMapObjectsResponse.<init>(GetMapObjectsResponseOuterClass.java:51)
                    at POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass$GetMapObjectsResponse$1.parsePartialFrom(GetMapObjectsResponseOuterClass.java:759)
                    at POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass$GetMapObjectsResponse$1.parsePartialFrom(GetMapObjectsResponseOuterClass.java:754)
                    at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:197)
                    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
                    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
                    at POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass$GetMapObjectsResponse.parseFrom(GetMapObjectsResponseOuterClass.java:222)
                    at com.pokegoapi.api.map.Map$6.handle(Map.java:299)
                    at com.pokegoapi.api.map.Map$6.handle(Map.java:294)
                    at com.pokegoapi.util.FutureWrapper.getResult(FutureWrapper.java:78)
                    at com.pokegoapi.util.FutureWrapper.get(FutureWrapper.java:53)
                    at com.pokegoapi.util.FutureWrapper.getResult(FutureWrapper.java:78)
                    at com.pokegoapi.util.FutureWrapper.get(FutureWrapper.java:53)
                    at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:108)
                    at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:94)
                    at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:122)
                    at

**Comment by vmarchaud** [comment]
Error from parsing the response from official servers, the problem come from protobuf directly not our lib.
