### ISSUE TITLE
java.lang.VerifyError While logging in

### ISSUE THREAD

**Issue by dylanmthompson** [Grover-c13/PokeGOAPI-Java#413]
**Description:**
Getting a java.lang.VerifyError when trying login using PTC.
I'm running the very latest code, just checked out a few hours ago

**Stacktrace (If it's a crash):**
`Exception in thread "PokeTrackThread" java.lang.VerifyError: class POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass$RequestEnvelope$AuthInfo$Builder overrides final method setUnknownFields.(Lcom/google/protobuf/UnknownFieldSet;)Lcom/google/protobuf/GeneratedMessage$Builder;
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass$RequestEnvelope$AuthInfo.toBuilder(RequestEnvelopeOuterClass.java:1030)
    at POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass$RequestEnvelope$AuthInfo.newBuilder(RequestEnvelopeOuterClass.java:1024)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:108)
    at com.dylan.Track.getNearby(Track.java:39)
    at com.dylan.TrackThread.run(TrackThread.java:50)`

**Code causing the issue:**
`
PokemonGo go = new PokemonGo(new PtcCredentialProvider(httpClient, "someusername", "somepassword", systemTime), httpClient, systemTime);
`

**Comment by Jasper-ketelaar** [comment]
I had this exact error yesterday. I reimported my project and it worked again magically, haven't a clue what exactly caused it but if it's bugging you maybe try that?

**Comment by vmarchaud** [comment]
Maybe that protobuf is just drunk ?

**Comment by Grover-c13** [comment]
maybe recompile the protos, i cant recreate this issue.
