### ISSUE TITLE
More Google Refresh Token Issues

### ISSUE THREAD

**Issue by KyleBoyer** [Grover-c13/PokeGOAPI-Java#474]
Stack Trace:

Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:215)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vmarchaud** [comment]
do you have any way to reproduce this @KyleBoyer google login is working fine for me ?

**Comment by Sieberkev** [comment]
I have the same, use a Google 2FA (app password), it throws these exceptions **exactly after 1h30min**.

```
07 aug 22:03:29 (default): Logged in successfully
.....
D/RequestHandler: Authenticated with static token
07 aug 23:33:32 (default: ProfileLoop): Failed to update profile and inventories
D/RequestHandler: Authenticated with static token
07 aug 23:33:33 (default: ProfileLoop): Error running loop ProfileLoop!

```

... every time, 100% reproducable :cry:

**Comment by vmarchaud** [comment]
You should update to latest, this issue has been resolved in dev branch few days ago.

**Comment by Sieberkev** [comment]
Myez... Jabbink's bot already is on commit `ef1f52f1f0621f94b97125975c961a8ad8129e92`(= the current dev at this moment) :smile:
