### ISSUE TITLE
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 

### ISSUE THREAD

**Issue by KyleBoyer** [Grover-c13/PokeGOAPI-Java#530]
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.api.map.fort.Pokestop.loot(Pokestop.java:172)
        at ink.abb.pogo.scraper.tasks.LootOneNearbyPokestop.run(LootOneNearbyPokestop.kt:39)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:51)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:149)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:187)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 10 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vmarchaud** [comment]
You might be softbanned/ipbanned, please retry with another ip/account.
