### ISSUE TITLE
NullPointer for Catch Pokemon

### ISSUE THREAD

**Issue by TheLushpen** [Grover-c13/PokeGOAPI-Java#536]
java.lang.NullPointerException: Attempt to invoke virtual method 'POGOProtos.Networking.Responses.CatchPokemonResponseOuterClass$CatchPokemonResponse$CatchStatus POGOProtos.Networking.Responses.CatchPokemonResponseOuterClass$CatchPokemonResponse.getStatus()' on a null object reference
                                            at com.pokegoapi.api.map.pokemon.CatchResult.getStatus(CatchResult.java:54)
                                            at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:712)
                                            at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:668)
                                            at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:631)
                                            at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:617)
                                            at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:604)

**Comment by ghost** [comment]
Same problem sometime at get vars on pokestop.

**Comment by FabianTerhorst** [comment]
#604
