### ISSUE TITLE
CatchablePokemon.catchPokemonWithBestBall throws exception

### ISSUE THREAD

**Issue by oorakci** [Grover-c13/PokeGOAPI-Java#577]
Hello,

CatchablePokemon.catchPokemonWithBestBall(true) method throws "Your account may be banned! please try from the official client." exception, if player has no razz_berry.

I think useItem(ItemId.ITEM_RAZZ_BERRY)  must called if player has razzbery.

com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.useItem(CatchablePokemon.java:847)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:695)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:647)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemonWithBestBall(CatchablePokemon.java:390)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemonWithBestBall(CatchablePokemon.java:360)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemonWithBestBall(CatchablePokemon.java:344)
    at pokebot.ai.api.PokemonGo.catchNearbyPokemons(PokemonGo.java:187)

**Comment by oorakci** [comment]
ItemBag.removeItem  also throws exception if count parameter is zero. This case can be controlled in the library.

**Comment by FabianTerhorst** [comment]
Try the new version this method doesn´t exist anymore.
