### ISSUE TITLE
Error Login Invalid Request

### ISSUE THREAD

**Issue by mackenzieg** [Grover-c13/PokeGOAPI-Java#585]
When trying to login I keep getting the following error. This only started within the last few hours... Did Niantic change something?

Stacktrace:

```
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token, body:error=invalid_request
at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:240)
at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:109)
at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:122)
at com.pokemongobot.Main.ptcAuthentication(Main.java:83)
at com.pokemongobot.Main.buildPokemonGo(Main.java:74)
at com.pokemongobot.BotRunner.run(BotRunner.java:20)
```

**Version:**
0.4

**Comment by FabianTerhorst** [comment]
Can you post your Code? This is a response when the Username or password is wrong.

**Comment by mackenzieg** [comment]
@FabianTerhorst 

```
 OkHttpClient client;

    if (option.getProxy() != null) {
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .proxy(new Proxy(Proxy.Type.HTTP, option.getProxy()));
        if (!option.getProxyCredentials().isEmpty()) {
            Authenticator proxyAuthenticator = (route, response) -> {
                String credential = option.getProxyCredentials();
                return response.request().newBuilder()
                        .header("Proxy-Authorization", credential)
                        .build();
            };
            builder.proxyAuthenticator(proxyAuthenticator);
        }
        client = builder.build();
    } else {
        client = new OkHttpClient();
}

CredentialProvider credentialProvider;
        credentialProvider = ptcAuthentication(client, option.getUsername(), option.getPassword());

private static CredentialProvider ptcAuthentication(OkHttpClient client, String username, String password) throws LoginFailedException, RemoteServerException {
    return new PtcCredentialProvider(client, username, password);
}
```

Here is the full thing:
https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/src/main/java/com/pokemongobot/Main.java

**Comment by Timenote** [comment]
Same here !

**Comment by mackenzieg** [comment]
@FabianTerhorst It appears to be a problem with different threads trying to login. I am now getting another problem, the map isn't being updated:

```
MapObjects(nearbyPokemons=[], catchablePokemons=[], wildPokemons=[], decimatedSpawnPoints=[], spawnPoints=[], gyms=[], pokestops=[], complete=false, api=com.pokegoapi.api.PokemonGo@76c5936e)
```

Notice the complete = false

**Comment by clangdev** [comment]
Maybe just another network or PTC-Offline Problem ;-)
https://github.com/Grover-c13/PokeGOAPI-Java/issues/391

No idea how they diagnosed my network settings, but it's not the API that is doing wrong..
Wish I had some more info in stacktrace to get this solved...

**Comment by mackenzieg** [comment]
@clangdev It was the PTC servers being down but now it seems I can't get any map data from the server... The MapObject always returns empty.

**Comment by FabianTerhorst** [comment]
This was a server issue.

**Comment by clangdev** [comment]
Is this still a server issue?
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token, body:error=invalid_request
    at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:240)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:109)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:122)
    at com.clangdev.pogoscanner.IVAnalyser.authenticate(IVAnalyser.java:342)
    at com.clangdev.pogoscanner.IVAnalyser.<init>(IVAnalyser.java:82)
    at com.clangdev.pogoscanner.IVAnalyser.main(IVAnalyser.java:354)

I get little bored with "your" standard solution: "It's the PTC, servers are down." or "It's you network, we do not know your network, but if it is not us.. it must be your network. Good luck."

```

enum Authtype {
        GOOGLE, PTC
    }

private PokemonGo authenticate(Authtype a, String user, String pass, String refreshtoken)
            throws LoginFailedException, RemoteServerException {
        PokemonGo back = null;

        OkHttpClient httpClient = new OkHttpClient();

        if (a.equals(Authtype.GOOGLE)) {
            if (refreshtoken == null) {
                GoogleUserCredentialProvider provider = new GoogleUserCredentialProvider(httpClient);


                System.out.println("Please go to " + GoogleUserCredentialProvider.LOGIN_URL);
                System.out.println("Enter authorisation code:");


                Scanner sc = new Scanner(System.in);
                String access = sc.nextLine();
                sc.close();

                provider.login(access);

                back = new PokemonGo(provider, httpClient);
                System.out.println("refreshtoken: " + provider.getRefreshToken());

            } else {
                back = new PokemonGo(new GoogleUserCredentialProvider(httpClient, refreshtoken), httpClient);
            }
        } else if (a.equals(
                Authtype.PTC)) {
            PtcCredentialProvider pcp = new PtcCredentialProvider(httpClient, username, password);
            System.out.println(pcp.getTokenId());

            back = new PokemonGo(pcp, httpClient);
        }
        System.out.println(back.getPlayerProfile().getPlayerData().getUsername() + " logged in successfully!");
        return back;
    }
```

using
PokeGOAPI-library-0.4.0.jar
