### ISSUE TITLE
New PokemonGO -> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by wpgabriel** [Grover-c13/PokeGOAPI-Java#591]
**Description:**
When trying to login with known good PTC credentials, my little test program fails. I attached my main class (renamed to GymStatus.java to GymStatus.txt so it would attach).

I have been using this login on the actual app and with PokeScanner (brought back to life thanks to your API). Those two continue to work for me, but when I run my program directly, I cannot log in.

It fails at PokemonGo go = new PokemonGo(auth, http); Won't be line 65 in the txt file since I took a couple of inconsequential lines out, but I can't seem to login.

**Stacktrace:**
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
    at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
    at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:111)
    at com.pgo.GymStatus.main(GymStatus.java:65)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
    ... 6 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 8 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
    at java.lang.Thread.run(Unknown Source)

**Version:**
0.4.0 (Cloned git repo this morning, 2016-08-15) and compiled by hand.

[GymStatus.txt](https://github.com/Grover-c13/PokeGOAPI-Java/files/418786/GymStatus.txt)

**Comment by FabianTerhorst** [comment]
You tried a different account and 3g connection?

**Comment by wpgabriel** [comment]
I'll try a different account shortly. I'm running this from my desktop, not a mobile device. I imagine that ethernet vs mobile wouldn't matter, right?

**Comment by wpgabriel** [comment]
I created a new PTC login, accepted ToS on PokemonGo app and tried my class main with the new login details and the error is exactly the same.

I should probably mention beyond having downloaded the API and compiling it, I was also sure the "git submodule update --init" in the PokeGOAPI-Java directory, then compiled with "gradlew :library:build" on Windows. Copied the resulting library/build/libs/PokeGOAPI-library-all-0.4.0.jar to my project's lib directory and included that in the classpath. Compiles and starts up fine but throws that error on new PokemonGo().

I'll try running my class with the same jar that I'm using in PokeScanner on my Mac on a different network and report back the results.

**Comment by wpgabriel** [comment]
It must be a problem with my Windows machine or its network. It worked on my Mac. Apologies for the bother.

Thanks again for all the great work on this project. You guys are amazing.

**Comment by ghost** [comment]
I have been continuously getting this on my Windows machine. Haven't tried this on any other environment. I'm able to reliably recreate this with transferring/evolving, but have also had it with egg incubation.

**Comment by nbulteau** [comment]
Same problem for on windows 10 : invalidProtocolBufferException: Contents of buffer are null
Does anyone has a clue ?

**Comment by nbulteau** [comment]
I just had a tempo between "my new PokemonGo" and my first request.

``` java
        PokemonGo go = new PokemonGo(provider, http);

        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            System.err.println(e.getMessage());
        }

        displayEggs(go);
```

**Comment by wpgabriel** [comment]
My original problem was with getting the null buffer trying to log in, not after a successful connection. And yes, it can still happen afterwards, but I have found that throttling requests to the server helps. I don't know what the rate is exactly (I've heard as low as 200ms), but I've had success with 500ms sleeps between server calls through the API.

Personally, I still get the null buffers on login occasionally, and adding some retry logic to the login sequence has fixed that problem for me.
