### ISSUE TITLE
Keep randomly getting AsyncPokemonGoException

### ISSUE THREAD

**Issue by Nyazuki** [Grover-c13/PokeGOAPI-Java#629]
**Description:**
Recently I found there is an increase sign of getting this `AsyncPokemonGoException` more and more often.

**Groovy:**

```
149  CredentialProvider auth = null
150
151  if(Login.signInMethods[choice] == "ptc") {
152    auth = new PtcCredentialProvider(http, Login.usernames[choice], Login.passwords[choice])
153  } else {
154    auth = new GoogleAutoCredentialProvider(http, Login.usernames[choice], Login.passwords[choice])
155  }
156
157  Thread.sleep(500);
158  PokemonGo go = new PokemonGo(auth, http);
159  Thread.sleep(500);
160
161  PlayerProfile playProfile = go.getPlayerProfile();
162  Thread.sleep(500);
163  Stats playerStats = playProfile.getStats();
164  Thread.sleep(500);
165  PlayerData playerData = playProfile.getPlayerData();
166  Thread.sleep(500);
```

**Stacktrace:**

```
D/RequestHandler: Authenticated with static token
E/Main: Failed to login or server issue: 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
  at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
  at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:157)
  at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:94)
  at com.pokegoapi.api.settings.Settings.<init>(Settings.java:81)
  at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:94)
  at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:112)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
  at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
  at GottaCatchemAll.main(GottaCatchemAll.groovy:158)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1445)
  at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:897)
  at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:287)
  at groovy.lang.GroovyShell.run(GroovyShell.java:518)
  at groovy.lang.GroovyShell.run(GroovyShell.java:507)
  at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
  at groovy.ui.GroovyMain.run(GroovyMain.java:384)
  at groovy.ui.GroovyMain.process(GroovyMain.java:370)
  at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
  at groovy.ui.GroovyMain.main(GroovyMain.java:109)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
  at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
  at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
  at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
  at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
  at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
  ... 37 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
  at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:111)
  at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:88)
  at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
  at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.Observable.subscribe(Observable.java:9957)
  at rx.Observable.subscribe(Observable.java:9924)
  at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
  ... 39 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
  at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
  at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:298)
  at java.lang.Thread.run(Thread.java:745)
```

**Version:**
0.4.0 - Development branch (https://github.com/Grover-c13/PokeGOAPI-Java/commit/adf27385ae4f6440bc13bf53023b790a1a937602)

**Comment by FabianTerhorst** [comment]
Duplicate with #542
