### ISSUE TITLE
Login with Google Credentials - fails

### ISSUE THREAD

**Issue by dustindevgroup** [Grover-c13/PokeGOAPI-Java#661]
**Description:**
The login with Google credentials is falling.
I'm using the example code, using the URL, and it used to work.
The account is not banned and still works with the app.
If I use an old refresh token, it works.

**Steps to reproduce:**
1. Try to login with a Google account using the example code.

**Expected behavior:**
Login with success and get a refresh token.

**Actual behavior:**
Login fails and there's no refresh token after provide.login( access ).
And provider.getRefreshToken() is always null.

**Stacktrace (If it's a crash):**

```
D/RequestHandler: Authenticated with static token
D/GoogleUserCredentialProvider: 0
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:157)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:85)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:72)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:112)
    at main.PokeBO.doLogin(PokeBO.java:119)
    at main.Main.startLoop(Main.java:75)
    at main.Main.main(Main.java:66)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: invalid_request
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
    ... 8 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: invalid_request
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:111)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:88)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 10 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: invalid_request
    at com.pokegoapi.auth.GoogleUserCredentialProvider.refreshToken(GoogleUserCredentialProvider.java:164)
    at com.pokegoapi.auth.GoogleUserCredentialProvider.getAuthInfo(GoogleUserCredentialProvider.java:242)
    at com.pokegoapi.api.PokemonGo.getAuthInfo(PokemonGo.java:124)
    at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:264)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:175)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:295)
    at java.lang.Thread.run(Thread.java:745)
```

**Version:**
Development branch

**Comment by dustindevgroup** [comment]
Getting bad request on this line:
`response = client.newCall(request).execute();`

Response{protocol=http/1.1, code=400, message=Bad Request, url=https://www.googleapis.com/oauth2/v4/token?........

**Comment by FabianTerhorst** [comment]
you setting a correct username and password?

**Comment by dustindevgroup** [comment]
I'm using the Google credentials, so I have to access that URL, login and copy the given code to the console.

```
GoogleUserCredentialProvider provider = new GoogleUserCredentialProvider(http);

// in this url, you will get a code for the google account that is logged
System.out.println("Please go to " + GoogleUserCredentialProvider.LOGIN_URL);
System.out.println("Enter authorisation code:");
```

I'm sure that username and password are correct. I can check some emails and stuff.

**Comment by FabianTerhorst** [comment]
and when you use GoogleAutoUserCredentialProvider?

**Comment by jay8ee** [comment]
I see this same issue, but only periodically.

**Comment by collinsmith** [comment]
I'm seeing a similar behavior. Shouldn't `GoogleUserCredentialProvider.login(String)` getting a `null` token throw a `LoginFailedException`?

```
D/GoogleUserCredentialProvider: 0
D/GoogleUserCredentialProvider: Got token: null
```
