### ISSUE TITLE
Proxy always fails: Failed to receive contents from server

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#688]
Hey there. 
I have a hard time connecting via Proxy!

**Description:**
Whenever I set a proxy (OkHttpClient.Builder.proxy(java.net.Proxy) I get a RemoteServer Exception: Failed to receive contents from server.

However, when i use the same OKHttpClient to open a URL-Connection to e.g. http://www.google.com everything works fine. Am I missing out something?!

**Stacktrace (If it's a crash):**

```
com.pokegoapi.exceptions.RemoteServerException: Failed to receive contents from server
    at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:143)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:109)
    at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:122)
    at server.PTCPlayerAccount.getCredentialProvider(PTCPlayerAccount.java:18)
...
```

**EDIT**: When getting the Credential Provider with a non-Proxy OkHttpClient i get the following error when instantiating PokemonGo:

```
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
    at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
    at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:111)
```

I have really no Idea how to deal with this one :o

Thanks in advance!

Greetings!

**Comment by ghost** [comment]
Heya guys! 

Sorry for this one! I solved it. Seems like I messed up the timeout settings and therefore the connection always failed (not responding in time).

Thanks ^_^
