### ISSUE TITLE
Error when catching Pokemon in CatchPokemonAtAreaExample

### ISSUE THREAD

**Issue by quentaurus** [Grover-c13/PokeGOAPI-Java#699]
**Description:**
Error when catching a pokemon in CatchPokemonAtAreaExample. Other parts of the API works (i.e. looting stops) and everything in the official client works for this account so this is not at ban.

**Steps to reproduce:**
Run CatchPokemonAtAreaExample in sample.

**Expected behavior:**
A pokemon is caught

**Actual behavior:**
A crash

**Stacktrace (If it's a crash):**
D/RequestHandler: Authenticated with static token
Pokemon in area:1
Encounted:PARAS
Exception in thread "main" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.useItem(CatchablePokemon.java:933)
    at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:563)
    at com.pokegoapi.examples.CatchPokemonAtAreaExample_01.main(CatchPokemonAtAreaExample_01.java:80)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
    ... 3 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:1)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 5 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:223)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
    at java.lang.Thread.run(Unknown Source)

**Version:**
0.4.0

**Comment by AbandonedCart** [comment]
The error occurs at `.setSpawnPointId(getSpawnPointId())` but the actual cause is unclear.

**Comment by Animeshm77** [comment]
#697  is same issue.

**Comment by FabianTerhorst** [comment]
close because of duplicate
