### ISSUE TITLE
NPE when logging in

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#723]
**Description:**
When logging in, a NPE is thrown inside getActivitySignature because PokemonGo#activityStatus hasn't been set yet.

**Stacktrace:**
java.lang.NullPointerException
        at com.pokegoapi.api.PokemonGo.getActivitySignature(PokemonGo.java:353)
    at com.pokegoapi.util.Signature.setSignature(Signature.java:57)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:179)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
    at java.lang.Thread.run(Thread.java:745)

**Version:**
[https://github.com/Grover-c13/PokeGOAPI-Java/commit/7117fa52add3ca090123a75aeccb56195a0ea69f](url)

**Comment by LoungeKatt** [comment]
It will be resolved shortly

**Comment by AbandonedCart** [comment]
Resolved by https://github.com/Grover-c13/PokeGOAPI-Java/pull/724 and https://github.com/Grover-c13/PokeGOAPI-Java/pull/725
