### ISSUE TITLE
java.lang.NoSuchMethodError for Zenfone 2 device

### ISSUE THREAD

**Issue by tommywuhaojie** [Grover-c13/PokeGOAPI-Java#747]
**Description:**

I can reproduce the crash with NoSuchMethodError on Zenfone 2 device 100%, I have revisit it the old posts about this issue but couldn't really find the solution. Thanks for helping!

**Steps to reproduce:**
1. Login using google authentication key

**Error:**
Crash/login fails

**Stacktrace:**

java.lang.NoSuchMethodError: No virtual method getByte(Ljava/lang/Object;J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
    at net.jpountz.util.UnsafeUtils.readByte(UnsafeUtils.java:68)
    at net.jpountz.xxhash.StreamingXXHash32JavaUnsafe.getValue(StreamingXXHash32JavaUnsafe.java:49)
    at com.pokegoapi.util.Signature.getLocationHash1(Signature.java:93)
    at com.pokegoapi.util.Signature.setSignature(Signature.java:39)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:179)
    at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:221)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
    at java.lang.Thread.run(Thread.java:818)

**Version:**
0.4.0

**Comment by broach** [comment]
The current code in Development does not have this issue:

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/util/Signature.java#L97

Looks like it was a commit from 14 days ago:

https://github.com/Grover-c13/PokeGOAPI-Java/commit/172a771ef7a221a4acf81237d6c68add021b9d0c
