### ISSUE TITLE
"Contents of buffer are null" exceptions

### ISSUE THREAD

**Issue by clangdev** [Grover-c13/PokeGOAPI-Java#869]
**Description:**
For some Pokemon I get "Contents of buffer are null" exceptions, like when setting a nickname to Ninetails (in german "Vulnona").

with "latest" GroverC13 PokeGOAPI-Java.

**Steps to reproduce:**

Setting nickname 1080Vulnona to NINETALES
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:81)
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:79)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:47)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:173)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:130)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:100)
	at com.pokegoapi.api.pokemon.Pokemon.renamePokemon(Pokemon.java:141)
	at com.clangdev.pogoscanner.PokeBot$PokeMod.modify(PokeBot.java:2290)
	at com.clangdev.pogoscanner.PokeBot.renamePokemon(PokeBot.java:521)
	at com.clangdev.pogoscanner.PokeBot.<init>(PokeBot.java:701)
	at com.clangdev.pogoscanner.PokeBot.main(PokeBot.java:2439)
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:120)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:97)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	... 8 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:89)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:381)
	at java.lang.Thread.run(Thread.java:745)
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:81)
	at com.pokegoapi.util.AsyncHelper.handleBlockingException(AsyncHelper.java:79)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:47)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:173)
	at com.pokegoapi.api.map.Map.requestMapObjects(Map.java:103)
	at com.pokegoapi.api.map.Map.update(Map.java:70)
	at com.pokegoapi.main.Heartbeat.beat(Heartbeat.java:96)
	at com.pokegoapi.main.Heartbeat$1.run(Heartbeat.java:70)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:120)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:97)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	... 6 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:89)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:381)
	... 1 more

**Comment by Gegy** [comment]
Update to the latest version of my fork.

**Comment by clangdev** [comment]
Problem is that your fork has some more serious problem than this. 
I already commented your latest commit.
Maybe there is a new parameter to set anywhere I do not know yet.
