### ISSUE TITLE
Unknown exception occurred

### ISSUE THREAD

**Issue by jinbuilds** [Grover-c13/PokeGOAPI-Java#894]
**Description:**
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 

Wondering if this is happening because of the latest update to PokemonGO Api.

**Steps to reproduce:**

OkHttpClient httpClient = new OkHttpClient();
PokemonGo go = new PokemonGo(httpClient);
go.login(new GoogleUserCredentialProvider(httpClient, REFRESH_TOKEN)); // It doesn't matter if you use or not a refresh token, it fails both ways

**Expected behavior:**
It must login user

**Actual behavior:**
Exception happens executing this line:
Class: PlayerProfile
Line: api.getRequestHandler().sendServerRequests(getPlayerServerRequest);

**Stacktrace (If it's a crash):**
D/RequestHandler: Authenticated with static token
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:103)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:88)
	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:160)
	at com.pokemon.crawler.app.PokeGoApiExample.loginWithRefreshToken(PokeGoApiExample.java:53)

**Version:**
compile 'com.pokegoapi:PokeGOAPI-library:0.4.1'

**Comment by Gegy** [comment]
Could you send the full stacktrace (AsyncPokemonGoException cause)?

**Comment by Gegy** [comment]
You need to compile the library from this source.
