### ISSUE TITLE
NoHttpResponseException

### ISSUE THREAD

**Issue by DominikTrenz** [Grover-c13/PokeGOAPI-Java#9]
I just tried this example:

auth = new GoogleLogin().login("username","password");
PokemonGo go = new PokemonGo(auth);
System.out.println(go.getPlayerProfile());

The authentications seems to work but i always end up with this exception:

```
org.apache.http.NoHttpResponseException: pgorelease.nianticlabs.com:443 failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at com.pokegoapi.main.RequestHandler.sendRequests(RequestHandler.java:76)
    at com.pokegoapi.api.PokemonGo.getInventory(PokemonGo.java:64)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:35)
    at com.pokegoapi.api.Main.main(Main.java:13)
```

**Comment by vmarchaud** [comment]
`pgorelease.nianticlabs.com:443 failed to respond` has you can read, its the niantic backend server that doesnt respond. Not an bug from client side.

**Comment by DominikTrenz** [comment]
Allright thank you. This error is gone but a new one appeared:

```
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: items[1].item.PlayerStats.PrevLevelExp, items[1].item.PlayerStats.KmWalked, items[1].item.PlayerStats.NumEvolutions, items[1].item.PlayerStats.NumberOfPokeballThrown, items[1].item.PlayerStats.NumEggsHatched, items[1].item.PlayerStats.BigMagikarpCaught, items[1].item.PlayerStats.NumBattleAttackWon, items[1].item.PlayerStats.NumBattleAttackTotal, items[1].item.PlayerStats.NumBattleDefendedWon, items[1].item.PlayerStats.NumBattleTrainingWon, items[1].item.PlayerStats.NumBattleTrainingTotal, items[1].item.PlayerStats.PrestigeRaisedTotal, items[1].item.PlayerStats.PrestigeDroppedTotal, items[1].item.PlayerStats.NumPokemonDeployed, items[1].item.PlayerStats.SmallRattataCaught
    at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
    at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    at com.pokegoapi.main.Inventory$InventoryResponseProto.parseFrom(Inventory.java:4481)
    at com.pokegoapi.requests.InventoryRequest.handleResponse(InventoryRequest.java:52)
    at com.pokegoapi.main.RequestHandler.sendRequests(RequestHandler.java:101)
    at com.pokegoapi.api.PokemonGo.getInventory(PokemonGo.java:64)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:35)
    at com.pokegoapi.api.Main.main(Main.java:13)
```

Any idea how to fix it?

**Comment by Grover-c13** [comment]
Im swapping all the proto stuff over to proto3 tonight, ive been compiling with proto2. Should fix it

**Comment by jabbink** [comment]
Oh, sorry @Grover-c13, didn't see this issue before. I switched to proto3 in #13

**Comment by Grover-c13** [comment]
All good
