### ISSUE TITLE
Cant Login with PTC/Google

### ISSUE THREAD

**Issue by DrBrad** [Grover-c13/PokeGOAPI-Java#939]
**Description:**
Not able to login to ptc/google

**Steps to reproduce:**

PokemonGo go = new PokemonGo(httpClient);
go.login(new PtcCredentialProvider(httpClient, "NAME", "PASSWORD"));

**Expected behavior:**
Logs in

**Actual behavior:**
Doesn't

**Stacktrace (If it's a crash):**
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:103)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:88)
	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:160)
	at com.drbradtech.pgtest.Main.main(Main.java:39)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 7 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
	at java.lang.Thread.run(Thread.java:745)

**Version:**
0.4.1

**Comment by Gegy** [comment]
You'll need to build from source for this to work.
