### ISSUE TITLE
Error Attacking Gym

### ISSUE THREAD

**Issue by bigperson5** [Grover-c13/PokeGOAPI-Java#946]
#**Description:**
Error Attacking Gym with the provided example

**Expected behavior:**
Gym is attacked

**Actual behavior:**
Exit of the main without battle

**Stacktrace (If it's a crash):**
com.pokegoapi.exceptions.request.RequestFailedException: com.pokegoapi.exceptions.request.RequestFailedException: Failed to send request: INVALID_REQUEST
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:36)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:167)
	at com.pokegoapi.api.gym.Battle.beginDefenderBattle(Battle.java:222)
	at com.pokegoapi.api.gym.Battle.start(Battle.java:175)
	at pok.main.attack(main.java:250)
	at pok.main.main(main.java:79)
Caused by: com.pokegoapi.exceptions.request.RequestFailedException: Failed to send request: INVALID_REQUEST
	at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:286)
	at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:188)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:400)
	at java.lang.Thread.run(Unknown Source)

**Version:**
0.4.1

**Comment by rakuuhwa** [comment]
Same error on API:7904 with ver 0.4.1. Also when char travels to the gym, and also when standing on top of the gym.

com.pokegoapi.exceptions.request.RequestFailedException: com.pokegoapi.exceptions.request.RequestFailedException: Failed to send request: INVALID_REQUEST
